# The west manifest file (west.yml) for the Find My Network (FMN) ADK.
#
# The per-workspace west configuration file, ncs/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = nrf
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  # This west.yml requires west 0.7 or later, because the "import"
  # feature used below was introduced then.
  version: 0.7

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  projects:

    # Import the nRF Connect SDK project.
    #
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/index.html
    - name: nrf
      repo-path: sdk-nrf
      revision: v1.5.0
      import: true


  # West-related configuration for the fmn repository.
  self:
    # This repository should be cloned to ncs/fmn.
    path: fmn
