//
// Copyright (c) 2020 Nordic Semiconductor ASA. All Rights Reserved.
//
// The information contained herein is confidential property of Nordic Semiconductor ASA.
// The use, copying, transfer or disclosure of such information is prohibited except by
// express written agreement with Nordic Semiconductor ASA.
//

pipeline
{
    environment {
        HOME="$WORKSPACE"
    }
    agent {
        docker {
            image 'docker-dtr.nordicsemi.no/sw-production/ncs-int:2.5.0'
            label 'build-node' // label of jenkins node to be used
        }
    }

    stages {

        stage('Prepare Python and fmntools') {  steps { script {
            sh "python -m pip install --user jinja2"
            sh "python -m pip install --user ssh"
            sh "python3 -m pip install --user markdown pygments"
            sh "python3 -m pip install --user tools/."
        } } }

        stage('Create repo folder') { steps { script { sh "mkdir fmn && shopt -s extglob && shopt extglob" } } }

        stage('Move repo') { steps { catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS') { sh "mv -f * fmn" } } }

        stage('West init') { steps { script { sh "west init -l fmn && west update" } } }

        stage('Build FMN') { steps { script { sh "west build fmn/apps/simple -b nrf52840dk_nrf52840" } } }

        stage('Build crypto') { steps { script { sh "west build --build-dir=build/build-crypto fmn/tests/crypto -b nrf52840dk_nrf52840" } } }




    } //stages

    post {
        always {
            script {
                    echo "Skiped stage for test"
                    archiveArtifacts artifacts: 'build/**/*', allowEmptyArchive: false
            }
        }
        cleanup { cleanWs disableDeferredWipeout: true, deleteDirs: true }
    } //post
} //pipeline
